project_name: std-buildr
builds:
  - binary: std-buildr
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
archive:
  format: tar.gz
  name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-sha256-checksums.txt"
sign:
  artifacts: all
release:
  disable: true
puts:
  - name: nexus
    target: https://nexus.cloudhomo.afip.gob.ar/nexus/repository/factura-blockchain-raw/std/{{ .ProjectName }}/{{ .Version }}/
    checksum: true
    mode: archive
    signature: false
    trusted_certificates: |
      -----BEGIN CERTIFICATE-----
      MIIENDCCAxygAwIBAgIIdbJxiCcSaTUwDQYJKoZIhvcNAQENBQAwNzEZMBcGA1UE
      AwwQQUZJUC1TU0wtQ0EtVEVTVDENMAsGA1UECgwEQUZJUDELMAkGA1UEBhMCQVIw
      HhcNMTcwNjEzMTU0NDQ5WhcNMTkwNjEzMTU0NDQ5WjBQMSAwHgYDVQQDDBcqLmNs
      b3VkaG9tby5hZmlwLmdvYi5hcjEQMA4GA1UECwwHU0RHIFNJVDENMAsGA1UECgwE
      QUZJUDELMAkGA1UEBhMCQVIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
      AQDODB60wa1LzAabxqEhatIJM7Q+5gsQR4kwuP67PSLgoDB+sc5BW7GSAnLKkp2h
      Hera2cOFczJE2XbVlehBdN9W5/1pODCH/3FcTPdPVXosV5pz4VRnVzCFmtrgfqt6
      OLX4RO+FFlhWkOsa0ECPmWv/4eWwyvX8IzsJL/4i7yYxr5nGO5hdOQy709jnjwne
      YHqU+h8vYgcd4C7JDL5dNOqQa3A+53gYuYIaeJXSH03JVeuNQlV0pAxw4sg5Kq6P
      nsXcfhz7ia/mOb46SVe5g5nznS5OodVLKT8gnmqgnWFAKP7SccSx16theSn8My5f
      bZHwPGlkfMrpEB4XT8jTJiuLAgMBAAGjggEpMIIBJTAMBgNVHRMBAf8EAjAAMB8G
      A1UdIwQYMBaAFGVYYVWji7SGc55OCfRFogY0BH9zMEEGCCsGAQUFBwEBBDUwMzAx
      BggrBgEFBQcwAYYlaHR0cDovL2F1dGhob21vLWV4dC5hZmlwLmdvYi5hci9vY3Nw
      LzAiBgNVHREEGzAZghcqLmNsb3VkaG9tby5hZmlwLmdvYi5hcjATBgNVHSUEDDAK
      BggrBgEFBQcDATBJBgNVHR8EQjBAMD6gPKA6hjhodHRwOi8vYXV0aGhvbW8tZXh0
      LmFmaXAuZ29iLmFyL2NybC9hZmlwLXNzbC1jYS10ZXN0LmNybDAdBgNVHQ4EFgQU
      AZq5pY44RcXaMNXN7jPElqDkF+EwDgYDVR0PAQH/BAQDAgXgMA0GCSqGSIb3DQEB
      DQUAA4IBAQA5oIZc31Y6OKUFVQj/TNhbN/2ALN0xb4+W3TXvd2b2t8FZDYEbowsd
      8fCBBdsXaaozutqsw04dLeDuHDWdV+7UISohhtBwtLGOsqWpZ/tlbUdQ+F/4xlIu
      ISSP1qorFMK2pfr/EYQ1frGmPlavSnVkaZxs/aHznqTwEKPLeWKfV4g/XzNk/+es
      DBJDWbk1mJaJ7xKeJjak1Hvq7hjv2i3tfW0jLPWCggaClGoZV2eXOjsEkmaCCXGU
      ja5BXtE+9LqBE3Xjb8DieV7qA0jS0/QDzrCbi5YTa5Xuux63aK/ZawofGf7UZ15t
      M0Q8Fl1bbtgWzHqo0R5H18WSDLCjlW3O
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIID4DCCAsigAwIBAgIIWuvv00uJWoUwDQYJKoZIhvcNAQENBQAwMzEVMBMGA1UE
      AwwMQUMgUmFpeiBUZXN0MQ0wCwYDVQQKDARBRklQMQswCQYDVQQGEwJBUjAeFw0x
      NjA5MDkxOTAzMzZaFw0yNDA5MDkxOTAzMzZaMDcxGTAXBgNVBAMMEEFGSVAtU1NM
      LUNBLVRFU1QxDTALBgNVBAoMBEFGSVAxCzAJBgNVBAYTAkFSMIIBIjANBgkqhkiG
      9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl3HLW6EHq34oLZ7uh6azAdekxuhVvOrRaHbN
      SErQt6qDqIPm2xbMIJu392RqkG487LSiPBT2OpZQHxio993DdUKLFxfxSm3GDXoS
      3CYCATjagsPnnNXFK0zzuIuB2dDcfcNc/l4A8EUI81an0z95R5ok2lKY0cmxwazl
      7Z21pfV9ncqinvuEFmZfQmro9V/NWkq2Y0v8c7PRli62d+Xz1bqdfxBt/yGAkOiR
      pXgXDnL4P4u36tTxv9z4ftO0yChW4hibAdxmNCIhh3n15f+ZxVpMOeORyNjjz+4S
      1Jz9zFQnDgwG4V/oOdhOFSeaAyr136hMQckIBCrNGmWzGl7FCQIDAQABo4HzMIHw
      MA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAU6hIkfATWiU2Mg3WiJooJHRn8
      nKswQQYIKwYBBQUHAQEENTAzMDEGCCsGAQUFBzABhiVodHRwOi8vYXV0aGhvbW8t
      ZXh0LmFmaXAuZ29iLmFyL29jc3AvMEoGA1UdHwRDMEEwP6A9oDuGOWh0dHA6Ly9h
      dXRoaG9tby1leHQuYWZpcC5nb2IuYXIvY3JsL2FmaXAtcm9vdC10ZXN0LWNhLmNy
      bDAdBgNVHQ4EFgQUZVhhVaOLtIZznk4J9EWiBjQEf3MwDgYDVR0PAQH/BAQDAgGG
      MA0GCSqGSIb3DQEBDQUAA4IBAQBmYkhaXkWfKlrds/oW6i286o9mQ7HCrvb4Yamg
      68fBFddFurmJ0dy1gEgBnDxtrS7yialtnxJ7kdIZxr8si+TbYnkVrUd7WmCt1uf1
      K3k1l6Vlt5qeU4Qw/FSthvJWJsRlWLALgspup5e354dSR4n1nVlr66lo8m7Gse0W
      tSkA6VU9gC7RgQC6USDiRbPlqzy7jBPu2VRqizsVD6VU5F0LmyhPewr+D92IMwnp
      8WDZ6g+A8zUbKNzEODzzrycRm12abLwwJPd9RGpax1ACZjfPFYhG87Nc3eNF6I6T
      SQScDEUmIKb/1wxHfP/rhmCmAGHiYszHaxStNz+lM+cqSduM
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIDSzCCAjOgAwIBAgIIOJx/arkZfLowDQYJKoZIhvcNAQENBQAwMzEVMBMGA1UE
      AwwMQUMgUmFpeiBUZXN0MQ0wCwYDVQQKDARBRklQMQswCQYDVQQGEwJBUjAeFw0x
      NDA2MDUxMzQ4NTZaFw0zNDA2MDYwMDAwMDBaMDMxFTATBgNVBAMMDEFDIFJhaXog
      VGVzdDENMAsGA1UECgwEQUZJUDELMAkGA1UEBhMCQVIwggEiMA0GCSqGSIb3DQEB
      AQUAA4IBDwAwggEKAoIBAQDABEDpCYyNVpRfsPD95oxAdAWIWiuKdbCOQY92L/ZN
      pceRRIUhzidYRxi9bo6ZFR6tC/0njN9/Lm6Zfrc/vrps7Z+wtlo0zAeWNEDOcdny
      NtbMcAmM1wIn9oValyWCG178vlkiZimBurVbZj6NJDa92bc4eJOFcYx6QTHJAstD
      JQISRnpzTce+XG7ERk8vYkx1z40NAD4iM5HOtIJdsLKx2Ju2Plr/8hI7NC0maJbC
      ckQfHOzSJkL0SMpI0CqpEL7008m6F5i1/CjfvFaXj68pQrS0Piqz8fvi3MuAvoAT
      MddEFKn/xdbbP5G+lvQjNzbw34P6uHONAStVB8BhnAdzAgMBAAGjYzBhMB0GA1Ud
      DgQWBBTqEiR8BNaJTYyDdaImigkdGfycqzAPBgNVHRMBAf8EBTADAQH/MB8GA1Ud
      IwQYMBaAFOoSJHwE1olNjIN1oiaKCR0Z/JyrMA4GA1UdDwEB/wQEAwIBhjANBgkq
      hkiG9w0BAQ0FAAOCAQEAlAEaxnLodTy74wPn0OUlSijy86zEwI4z+U5q1S+C3RVs
      bl4qZM+G5/4yFChqbEx1aH2TaS8ETimtHkayAz8nyZdOJ6VWBtz/E9S0cjnTUfa9
      TdrB6p7Q9lDDSYV0+KBodXOYXuOjfCms6K7FDFBfQq/OqV2es28yfoazjWWnnIWf
      zZ72vkL8E6A4t3qhoXyBzUuwQQL58t4ZCF7k0U0xzyYUAl/jmg+IsEjZ3LAvW/zx
      827MdsFGIXRqc1RNkS2PPmtzzoSbS++tTXqGrU3SywqH0eb31Lv2PQ6S3usFP2YD
      pgFCPRntmLKe6Mn0z6qstEsqoKueslDoRNZdb2x+bg==
      -----END CERTIFICATE-----
