project_name: std-buildr
builds:
  - binary: std-buildr
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
archive:
  format: tar.gz
  name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-sha256-checksums.txt"
sign:
  artifacts: all
release:
  disable: true
puts:
  - name: nexus
    target: https://nexus.cloudint.afip.gob.ar/std-raw/std/{{ .ProjectName }}/{{ .Version }}/
    checksum: true
    signature: true
    username: plalloni
